// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataSourceType = { "SQLITE": { connection_string: string, } } | { "PSQL": { connection_string: string, } } | { "MARIA_DB": { connection_string: string, } };
