// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EntityFieldType = { "TEXT": { min: number, max: number, validate: string, generate: string, } } | { "NUMBER": { min: number, max: number, is_int: boolean, } } | "BOOL" | { "DATE": { min_date: string, max_date: string, } } | { "RELATION": { entity_name: string, } } | { "RELATION_MANY": { entity_names: Array<string>, } };
