// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityField } from "./EntityField";
import type { EntityType } from "./EntityType";

export type Entity = { uuid: string, name: string, kind: EntityType, fields: { [key in string]?: EntityField }, };
