// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityRecord } from "./EntityRecord";

export type EntityFieldRecord = string | number | boolean | string | EntityRecord | Array<EntityRecord>;
