// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityFieldRecord } from "./EntityFieldRecord";
import type { EntityFieldType } from "./EntityFieldType";

export type EntityField = { name: string, nullable: boolean, base: boolean, primary_key: boolean, kind: EntityFieldType, default_value: EntityFieldRecord | null, };
