// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Entity } from "./Entity";
import type { SchemaSettings } from "./SchemaSettings";

export type Schema = { version: string, entities: Array<Entity>, settings: SchemaSettings, };
